import AllProvider from "@/Provider/AllProvider";
import Navbar from "@/component/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AllProvider>
          <Navbar />
          {children}
        </AllProvider>
      </body>
    </html>
  );
}
